Repository Cloud-Engineering2/project2-team1, pull requests merged in 2025-02, with the labels that each got.

#3 Feat: Exception Handler 추가
  src/main/java/project2/exception/ErrorResponse.java
  src/main/java/project2/exception/GlobalExceptionHandler.java
  src/main/java/project2/exception/ImageUploadException.java
  src/main/java/project2/exception/PostNotFoundException.java
Labels: feature

#8 Feat: API for post deletion
  src/main/java/project2/controller/PostController.java
  src/main/java/project2/service/PostService.java
Labels: feature

#15 Feat: CRUD for comment
  src/main/java/project2/config/PrincipalDetails.java
  src/main/java/project2/config/SecurityConfig.java
  src/main/java/project2/controller/CommentController.java
  src/main/java/project2/controller/CommentsController.java
  src/main/java/project2/dto/CommentCreateRequest.java
  src/main/java/project2/dto/CommentRequest.java
  src/main/java/project2/dto/CommentResponse.java
  src/main/java/project2/entity/Comments.java
  src/main/java/project2/exception/CommentNotBelongToPostException.java
  src/main/java/project2/exception/CommentNotFoundException.java
  src/main/java/project2/exception/GlobalExceptionHandler.java
  src/main/java/project2/exception/UnauthorizedException.java
  src/main/java/project2/service/CommentService.java
Labels: feature

#19 Feat: Upload multi file to post
  src/main/java/project2/config/WebConfig.java
  src/main/java/project2/controller/PostController.java
  src/main/java/project2/dto/PostResponse.java
  src/main/java/project2/entity/Posts.java
  src/main/java/project2/service/PostService.java
Labels: feature

#24 Fix: Modify permission
  src/main/java/project2/config/JwtAuthorizationFilter.java
  src/main/java/project2/config/WebSecurityConfig.java
  src/main/java/project2/exception/GlobalExceptionHandler.java
  src/main/java/project2/service/CommentService.java
  src/main/java/project2/service/PostService.java
Labels: feature

#30 Fix: Resolve cascading issue
  src/main/java/project2/Application.java
  src/main/java/project2/controller/CommentController.java
  src/main/java/project2/controller/FrontController.java
  src/main/java/project2/controller/PostController.java
  src/main/java/project2/entity/Posts.java
  src/main/java/project2/service/PostService.java
  src/main/resources/templates/post-detail.html
Labels: bug, feature

#33 Fix: inquire post with response dto
  src/main/java/project2/controller/FrontController.java
  src/main/java/project2/controller/PostController.java
  src/main/java/project2/dto/CommentResponse.java
  src/main/java/project2/dto/PostResponse.java
  src/main/java/project2/service/CommentService.java
  src/main/java/project2/service/PostService.java
  src/main/resources/templates/post-detail.html
  src/main/resources/templates/post-list.html
  src/main/resources/templates/profile-edit.html
Labels: feature

#34 Fix: Modify location url to post-list page
  src/main/resources/templates/post-edit.html
Labels: bug

#35 Feat/post comment update delete
  src/main/java/project2/controller/CommentController.java
  src/main/java/project2/dto/CommentResponse.java
  src/main/java/project2/service/CommentService.java
  src/main/resources/templates/post-detail.html
Labels: feature

#36 Fix: Profile post
  src/main/java/project2/dto/PostResponse.java
  src/main/java/project2/service/PostService.java
  src/main/resources/templates/post-list.html
  src/main/resources/templates/profile.html
Labels: feature

#37 fix: Fixed an issue where the delete button was visible to users other than the post author
  src/main/resources/templates/post-detail.html
Labels: bug

#38 fix: post-create and post-edit profileBtn
  src/main/resources/templates/post-create.html
  src/main/resources/templates/post-edit.html
Labels: bug

#39 Feat: redirect page
  src/main/java/project2/controller/FrontController.java
  src/main/resources/templates/login.html
  src/main/resources/templates/profile.html
Labels: feature

#41 Fix: resolve user deletion issue
  src/main/java/project2/controller/UserController.java
  src/main/java/project2/dto/UserResponse.java
  src/main/java/project2/entity/Users.java
  src/main/java/project2/service/UserService.java
Labels: bug
